### ISSUE TITLE
Approved PR gets built twice on auto branch

### ISSUE THREAD

**Issue by bstaletic** [servo/homu#144]
I'm part of the team that's maintaining [YouCompleteMe](https://github.com/Valloric/YouCompleteMe) and [ycmd](https://github.com/Valloric/YouCompleteMe). We're using homu to merge our pull requests, but we've run into an annoying issue.

Once we approve a PR, it gets tested on the `auto` branch, then, provided, the tests passed, it is built and tested on `master`. So far so good.
The next time a PR is approved, homu would first trigger another build of the previously merged PR on the auto branch.

Also, this doesn't only happen on successful merges, but even on PR's whose tests fail.
To better show what I'm trying to explain, here's the travis history:
https://travis-ci.org/Valloric/ycmd/builds/

If you open the link and search for `#898` for example, you will see a build on auto, then master, then auto again.

I'm aware that this could be a misconfiguration on our end, so if it is I'd like to ask for help finding out what's wrong.

**Comment by Manishearth** [comment]
That seems weird. I'm looking at your settings and don't see anything off. Feels like a misconfiguration -- i don't see this pattern on other homu-using repos -- but I can't be sure.

**Comment by Valloric** [comment]
@Manishearth I can't see anything wrong with our homu config. Perhaps its a Travis config issue? I've included our homu config below (with secrets redacted).

```toml
[github]
access_token = "<redacted>"
app_client_id = "<redacted>"
app_client_secret = "<redacted>"

[web]
port = 54856
sync_on_start = true

[repo.ycmd]
owner = "Valloric"
name = "ycmd"

reviewers = []
auth_collaborators = true
try_users = []

[repo.ycmd.github]
secret = "<redacted>"

[repo.ycmd.status.travis]
context = 'continuous-integration/travis-ci/push'

[repo.ycmd.status.appveyor]
context = 'continuous-integration/appveyor/branch'

[repo.YouCompleteMe]
owner = "Valloric"
name = "YouCompleteMe"
reviewers = []
auth_collaborators = true
try_users = []

[repo.YouCompleteMe.github]
secret = "<redacted>"

[repo.YouCompleteMe.status.travis]
context = 'continuous-integration/travis-ci/push'

[repo.YouCompleteMe.status.appveyor]
context = 'continuous-integration/appveyor/branch'


[repo.EmacsYcmd]
owner = "abingham"
name = "emacs-ycmd"

reviewers = []
auth_collaborators = true
try_users = []

[repo.EmacsYcmd.github]
secret = "<redacted>"

[repo.EmacsYcmd.status.travis]
context = 'continuous-integration/travis-ci/push'

[repo.JediHTTP]
owner = "vheon"
name = "JediHTTP"

reviewers = []
auth_collaborators = true
try_users = []

[repo.JediHTTP.github]
secret = "<redacted>"

[repo.JediHTTP.status.travis]
context = 'continuous-integration/travis-ci/push'

[repo.JediHTTP.status.appveyor]
context = 'continuous-integration/appveyor/branch'

# The database homu uses
[db]

## SQLite file
file = "main.db"
```
